###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  mysql:
    image: mysql:5.7
    container_name: pentabee-api-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=pentabee-root
      - MYSQL_DATABASE=pentabee
      - MYSQL_USER=pentabee
      - MYSQL_PASSWORD=pentabee
    ports:
      - "7002:3306"

  webserver:
    image: nginx:alpine
    container_name: pentabee-api-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7000:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: phpdocker/php-fpm
    container_name: pentabee-api-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pentabee-api-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=http://pma.pentabee.local
    ports:
      - "7003:80"
    depends_on:
      - mysql
